version: 2.1

workflows:
  main:
    jobs:
      - test
      - publish:
          requires:
            - test

orbs:
  node: circleci/node@1.1.4

executors:
  node12:
    docker:
      - image: circleci/node:12

commands:
  setup:
    steps:
      - checkout:
          path: ..
      - node/with-cache:
          cache-key: package-lock.json
          steps:
            - run: npm ci

jobs:

  test:
    executor: node12
    working_directory: ~/project/trigger-pipeline
    steps:
      - setup

      - run:
          command: npm run prettier
          when: always

      - run:
          command: npm run typecheck
          when: always

      - run:
          name: npm test
          command: npm test -- --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

      - run:
          command: npm run build
          when: always
      - run:
          name: show bundled action
          command: cat action.bundle.js
      - persist_to_workspace:
          root: .
          paths:
            - action.bundle.js
      - store_artifacts:
          path: action.bundle.js

  publish:
    executor: node12
    working_directory: ~/project/trigger-pipeline
    steps:
      - setup
      - attach_workspace:
          at: .
      - run: cat action.bundle.js
