version: 2
workflows:
  version: 2
  workflow:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: forever
          command: |
            while true; do
              echo hi
              sleep 5
            done
